spring:
  main:
    web-application-type: REACTIVE
  application:
    name: zuulsvr
  profiles:
    active:
      default
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#    gateway:
#      routes:
#        - id: my_route
#          uri: https://example.org
#          predicates:
#            - Path=/v1/**
#          filter:
#            - StripPrefix=1
server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#zuul:
#  prefix:  /api
#  routes:
#  organizationservice: /organization/**
